# Demonstrating how github actions env vars work
---
name: demo-env-vars

on:
  pull_request_target:
    branches:
      - main
  push:
    branches: 
      - main
      - dev-env-vars

jobs:
  demo-env-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Show run with double and single quotes
        env:
          REPOSITORY_VAR: ${{ vars.REPOSITORY_VAR }}
        run: |
          "echo '$REPOSITORY_VAR'"
      - name: Show run with only double quotes
        env:
          REPOSITORY_VAR: ${{ vars.REPOSITORY_VAR }}
        run: |
          "echo $REPOSITORY_VAR"
      - name: Show run with double quotes only around env var
        env:
          REPOSITORY_VAR: ${{ vars.REPOSITORY_VAR }}
        run: |
          echo "$REPOSITORY_VAR"
      - name: Use GitHub Actions env vars with double quotes
        env:
          REPOSITORY_VAR: ${{ vars.REPOSITORY_VAR }}
        run: |
          echo "REPOSITORY_VAR=${REPOSITORY_VAR}" >> $GITHUB_ENV
      - name: Show the GitHub Actions environment var
        run: |
          echo "$REPOSITORY_VAR"
